development:
  fedex:
    key: O21wEWKhdDn2SYyb
    password: db0SYxXWWh0bgRSN7Ikg9Vunz
    account_number: 510087780
    meter: 119009727
    mode: test
  bunny:
    url: amqps://csaizoxi:qv_k0WA2C6LxW62pKsOnacjGQhgnBaXN@coyote.rmq.cloudamqp.com/csaizoxi
test:
  fedex:
    key: O21wEWKhdDn2SYyb
    password: db0SYxXWWh0bgRSN7Ikg9Vunz
    account_number: 510087780
    meter: 119009727
    mode: test